### ISSUE TITLE
Segmentation fault on setup for compiler.has_function() with dependencies

### ISSUE THREAD

**Issue by ma8ma** [annacrombie/muon#35]
Segmentation fault on setup for compiler.has_function() with dependencies

Hi, @annacrombie 

I found a crash on the setup subcommand. Here are the steps to reproduce it:

Build muon and show version
```bash
git clone --depth 1 -b master https://git.sr.ht/~lattis/muon
cd muon
./bootstrap.sh stage1
# There are no necessary dependencies to reproduce the segfault.
./stage1/muon setup -Ddocs=disabled -Dlibarchive=disabled -Dlibcurl=disabled -Dlibpkgconf=disabled stage2
./stage1/muon samu -C stage2
```
```bash
$ ./stage2/muon version
muon 0.2.0-bd2e191
meson compatibility version 1.1.99
enabled features:
  samurai
```

Prepare a sample project for reproducing the segfault.
```bash
mkdir sample_project
cd sample_project
cat <<EOF >meson.build
project('sample_project', 'c', version : '0.1')

dep = dependency('', required : false)
c_compiler = meson.get_compiler('c')
c_compiler.has_function('xxxxxx', dependencies : dep)
EOF
```

Proceed with the setup:
```bash
$ ../stage2/muon setup _build
detected compiler gcc '13.2.0' (['cc']), linker: ld (gnu) (['ld']), static_linker: ar (gcc) (['ar'])
configuring 'sample_project', version: 0.1
Segmentation fault (core dumped)
```

To further investigate the issue, I ran the command under gdb and obtained a backtrace:
```c
$ gdb --args ../stage2/muon setup _build
(gdb) run
(snip)
detected compiler gcc '13.2.0' (['cc']), linker: ld (gnu) (['ld']), static_linker: ar (gcc) (['ar'])
configuring 'sample_project', version: 0.1

Program received signal SIGSEGV, Segmentation fault.
push_linker_args (wk=0x7fffffffc310, ctx=0x7fffffffa4e0, args=0x5555556175f0 <args>) at ../src/backend/common_args.c:510
510             if (ctx->compiler->linker_passthrough) {
(gdb) p ctx
$1 = (struct setup_linker_args_ctx *) 0x7fffffffa4e0
(gdb) p ctx->compiler
$2 = (struct obj_compiler *) 0x0
(gdb) bt
#0  push_linker_args (wk=0x7fffffffc310, ctx=0x7fffffffa4e0, args=0x5555556175f0 <args>) at ../src/backend/common_args.c:510
#1  0x0000555555560e5c in setup_linker_args (wk=0x7fffffffc310, proj=0x0, tgt=0x0, ctx=0x7fffffffa4e0) at ../src/backend/common_args.c:613
#2  0x000055555556be7c in compiler_check (wk=0x7fffffffc310, opts=0x7fffffffaac0,
    src=0x7fffffffab70 "#define xxxxxx muon_disable_define_of_xxxxxx\n\n#include <limits.h>\n#undef xxxxxx\n#ifdef __cplusplus\nextern \"C\"\n#endif\nchar xxxxxx (void);\n#if defined __stub_xxxxxx || defined __stub___xxxxxx\nfail fail "..., err_node=3258, res=0x7fffffffaa4d)
    at ../src/functions/compiler.c:314
#3  0x000055555556dcca in func_compiler_has_function (wk=0x7fffffffc310, self=447, res=0x7fffffffbbe8) at ../src/functions/compiler.c:924
#4  0x00005555555ba8b3 in vm_native_func_dispatch (wk=0x7fffffffc310, func_idx=207, self=447, res=0x7fffffffbbe8) at ../src/lang/vm.c:1971
#5  0x00005555555b8f8f in vm_op_call_method (wk=0x7fffffffc310) at ../src/lang/vm.c:1316
#6  0x00005555555ba30b in vm_execute (wk=0x7fffffffc310) at ../src/lang/vm.c:1811
#7  0x000055555559c32b in eval (wk=0x7fffffffc310, src=0x555555636f50, mode=eval_mode_first, res=0x7fffffffbcf8) at ../src/lang/eval.c:143
#8  0x000055555559c5d4 in eval_project_file (wk=0x7fffffffc310,
    path=0x7fffffffbec0 "/home/ma8ma/var/src/muon/muon/sample_project/meson.build", first=true) at ../src/lang/eval.c:192
#9  0x000055555559bfb0 in eval_project (wk=0x7fffffffc310, subproject_name=0x0,
    cwd=0x55555565b9c0 "/home/ma8ma/var/src/muon/muon/sample_project",
    build_dir=0x55555565bfa2 "/home/ma8ma/var/src/muon/muon/sample_project/_build", proj_id=0x7fffffffc2f8) at ../src/lang/eval.c:65
#10 0x00005555555cf2c7 in cmd_setup (argc=3, argi=3, argv=0x7fffffffda08) at ../src/main.c:854
#11 0x00005555555cfebc in cmd_main (argc=3, argi=1, argv=0x7fffffffda08) at ../src/main.c:1066
#12 0x00005555555d002b in main (argc=3, argv=0x7fffffffda08) at ../src/main.c:1098
```

Expected setup result:
```bash
detected compiler gcc '13.2.0' (['cc']), linker: ld.bfd (['ld.bfd']), static_linker: ar (gcc) (['ar'])
configuring 'sample_project', version: 0.1
c compiler: has function xxxxxx: NO

setup complete
```

Please let me know if you need any further information to investigate this issue.

Thank you.

**Comment by ma8ma** [comment]
```bash
$ ./stage2/muon version
muon 0.2.0-20cafd21
meson compatibility version 1.1.99
enabled features:
  samurai
```
I have checked the update and confirmed that the segfault has been fixed. Thank you for your hard work! :+1:
